
services:
    my-nginx:
        image: nginx:alpine
        ports:
          - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

        depends_on:
          - my-node-1
          - my-node-2


    my-node-1:
        build: 
            context: ./backend
            dockerfile: "Dockerfile"

        environment:
            - CONTAINER_NAME=container-1

    my-node-2:
      build:
          context: ./backend
          dockerfile: "Dockerfile"

      environment:
          - CONTAINER_NAME=container-2