export const AUTHORS = [
  {
    img: "../author_images/Image1.svg",
    name: "Esthera Jackson",
    email: "esthera@simmmple.com",
    position: "Manager",
    heirarchy: "Organization",
    status: "online",
    date_of_employment: "14/06/21",
  },
  {
    img: "../author_images/Image2.svg",
    name: "Alexa Liras",
    email: "alexa@simmmple.com",
    position: "Programmer",
    heirarchy: "Developer",
    status: "offline",
    date_of_employment: "14/06/21",
  },
  {
    img: "../author_images/Image3.svg",
    name: "Laurent Michael",
    email: "laurent@simmmple.com",
    position: "Executive",
    heirarchy: "Projects",
    status: "online",
    date_of_employment: "14/06/21",
  },
  {
    img: "../author_images/Image4.svg",
    name: "Ferdurdo Hill",
    email: "ferdurdo@simmmple.com",
    position: "Manager",
    heirarchy: "Organization",
    status: "online",
    date_of_employment: "14/06/21",
  },
  {
    img: "../author_images/Image5.svg",
    name: "Daniel Thomas",
    email: "daniel@simmmple.com",
    position: "Programmer",
    heirarchy: "Developer",
    status: "offline",
    date_of_employment: "14/06/21",
  },
  {
    img: "../author_images/Image6.svg",
    name: "Mark Wilson",
    email: "mark@simmmple.com",
    position: "Designer",
    heirarchy: "UI/UX Design",
    status: "offline",
    date_of_employment: "14/06/21",
  },
];